apiVersion: v1
kind: Service
metadata:
  name: mcp-runtime-operator-webhook-service
  namespace: mcp-runtime
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager
