name: Security - Gosec

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  gosec:
    name: Gosec Scan
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@v2.26.1

      - name: Run gosec
        run: $(go env GOPATH)/bin/gosec ./...
