name: Security - Gosec

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  gosec:
    name: Gosec Scan
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@v2.26.1

      - name: Run gosec
        run: $(go env GOPATH)/bin/gosec ./...
